name: Closed PR injection

on:
  workflow_dispatch:


permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sets MODIFIED_BRANCH_NAME
        env:
          MODIFIED_BRANCH_NAME: ${{github.head_ref}}
        run: |
          echo "MODIFIED_BRANCH_NAME=;id" >> $GITHUB_ENV

      - run: rm -rf branch/$MODIFIED_BRANCH_NAME
