name: Test

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Tests
        run: echo Tests!
    
